/*
-- Query: SELECT * FROM learn_english.word
LIMIT 0, 1000

-- Date: 2020-03-30 18:06
*/
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (1,'pies','dog','GENERAL');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (2,'administrator','admin','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (3,'algorytm','algorithm','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (4,'aplikacja','application','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (5,'kopia zapasowa','backup','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (6,'przeglądarka','browser','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (7,'błąd w kodzie','bug','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (8,'obudowa','casing','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (9,'ładowarka, zasilacz','charger','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (10,'chmura','cloud','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (11,'kod','code','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (12,'komenda','command','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (13,'monitor komputera','computer monitor','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (14,'treść, zawartość','content','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (15,'panel sterowania','control panel','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (16,'procesor','CPU','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (17,'kursor','cursos','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (18,'wycinać','cut','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (19,'panel','dashboard','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (20,'dane','data','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (21,'baza danych','database','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (22,'debugowanie','debugging','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (23,'wdrażać do produkcji','deploy','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (24,'pulpit','desktop','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (25,'programista, developer','developer','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (26,'opracowywanie oprogramowania','development','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (27,'urządzeie','device','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (28,'dokument','document','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (29,'pobieranie','download','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (30,'przeciąganie','drag','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (31,'sterowniki','drivers','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (32,'edytować','edit','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (33,'szyfrowanie','encryption','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (34,'środowisko','environment','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (35,'błąd','error','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (36,'dysk zewnętrzny','external drive','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (37,'wentylator','fan','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (38,'cecha, funkcja ','feature','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (39,'opinia, wyniki','feedback','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (40,'plik','file','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (41,'folder','folder','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (42,'czcionka','font','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (43,'zawieszenie się komputera','freeze','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (44,'funkcjonalność','functionality','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (45,'dysk twardy','hard drive','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (46,'sprzęt','hardware','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (47,'pomoc','help','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (48,'zaznaczenie','highlight','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (49,'ikona','icon','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (50,'interfejs','interface','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (51,'dostęp do Internetu','Inter access','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (52,'dostawca Internetu','Internet provider','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (53,'klawiatura','keyboard','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (54,'skrót na klawiaturze','keyboard shortcut','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (55,'otwarcie aplikacji','launch','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (56,'układ','layout','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (57,'logować się','login','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (58,'wylogować się','logout','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (59,'megabajt','megabyte','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (60,'pamięć','memory','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (61,'platforma mobilna','mobile platform','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (62,'płyta główna','motherboard','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (63,'mysz','mouse','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (64,'podkładka pod mysz','mouse pad','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (65,'sieć','network','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (66,'otwarte oprogramowanie','open source software','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (67,'system operacyjny','operating system','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (68,'opcje','options','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (69,'partycja','partition','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (70,'hasło','password','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (71,'wklejać','paste','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (72,'komputer stacjonarny','personal computer','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (73,'wtyczka','plugin','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (74,'port','port','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (75,'zasilanie','power supply','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (76,'podgląd','preview','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (77,'język programowania','programming language','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (78,'kontrola jakości','quality assurance','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (79,'pamięć o dowolnym dostępie','random access memory','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (80,'zapisać','save','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (81,'zapisać jako','save as','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (82,'rozdzielczość ekranu','screen resolution','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (83,'przewijać','scroll','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (84,'pasek przewijania','scroll bar','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (85,'serwer','server','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (86,'oprogramowanie','software','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (87,'inżynieria oprogramowania','software engineering','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (88,'jakość oprogramowania','software quality','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (89,'karta dzwiękowa','sound card','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (90,'głośniki','speakers','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (91,'arkusz obliczeniowy','spreadsheet','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (92,'zapisać się','subscribe','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (93,'pomoc, obsłuha','support','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (94,'testowanie','testing','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (95,'pasek narzędzi','toolbar','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (96,'narzędzia','tools','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (97,'panel dotykowy','touchpad','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (98,'aktualizacja','update','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (99,'udostępnianie','upload','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (100,'port USB','usb port','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (101,'użytkownik','user','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (102,'karta graficzna','video card','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (103,'widżet','widget','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (104,'okno','window','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (105,'sieć bezprzewodowa','wireless network','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (106,'potwierdzenie','acknowledgement','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (107,'antywirus','antivirus','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (108,'załącznik','attachment','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (109,'kompatybilny','compatible','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (110,'nośnik danych','data carrier','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (111,'wyjście','escape','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (112,'dyskietka','floppy disk','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (113,'skrzynka pocztowa ','mailbox','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (114,'skrócony zapis','abbreviation','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (115,'analiza','analysis','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (116,'narzędzie wykonujące określone zadanie','appliance','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (117,'wyniknąć, pojawić się ','arise','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (118,'dostępny','available','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (119,'wygoda, komfort','convenience','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (120,'żadanie','demand','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (121,'mankament, wada, przeszkoda','drawback','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (122,'produktywny','efficient','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (123,'zmęczenie oczu','eye strain','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (124,'łączenie w całość','integrate','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (125,'szczery wobec kogoś','level with someone','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (126,'utrzymywać','maintain','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (127,'projektować','design','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (128,'modernizować','update','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (129,'obługiwać, działać na','run on','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (130,'wysypać się','crash','IT');
INSERT INTO `` (`id`,`polish`,`english`,`category`) VALUES (131,'ciasteczka','cookie','IT');
